image: /home/mmanueeelaadmin/turtlebot3_ws/src/pamabot/my_nav2_system/config/farmaciaMapa.pgm
mode: trinary
resolution: 0.05
origin: [-8.95, -17.2, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25
